- integration-tests/common/http.js
- integration-tests/rest-device.js
Changed expected error in tests. And fixed test with nonNetworkUser. Added new test.
> Changed expected error in tests.

- integration-tests/rest-device.js
Added test to check that admin without assigned networks, got 412 status code if he registers device without network.
> Defect/118. Registering device by admin without any assigned network.

- integration-tests/ws-client-notification.js
- integration-tests/ws-device-notification.js
Changed expected response body for web-sockets notifications. Added new test.
> defect/135 Changed expected response body for web-sockets tests.

- integration-tests/common/utils.js
> [defect/9]

- integration-tests/common/utils.js
- integration-tests/rest-jwt.js
- package.json
Added two tests to check assigning of user rights, when JWT token is
being creating
> Tests for JwtTokenService

- integration-tests/rest-user.js
Remove anonymous user creation
> Remove anonymous user creation

- integration-tests/common/utils.js
- integration-tests/rest-device.js
- package.json
> Fixes for the DeviceService updates

- integration-tests/rest-configuration.js
> Configuration API tests added

- integration-tests/rest-user.js
User login and password validation added
> Login password validation

- integration-tests/ws-device.js
Created test for ws device/list
> Created test for ws device/list

- integration-tests/common/utils.js
- integration-tests/rest-jwt.js
Error fixed when refresh with invalid signature (tests updated)
> Error fixed when refresh with invalid signature (tests updated)

- integration-tests/rest-user.js
Remove data for user  tests updated
> Remove data for user  tests updated

- integration-tests/ws-client-notification.js
Command notification/insert return error 500 fixed
> Command notification/insert return error 500 fixed

- integration-tests/ws-device.js
[ws] device/get command return 500 update
> [ws] device/get command return 500 update

- integration-tests/ws-notification.js
Device id is required for notification insert
> Device id is required for notification insert

- integration-tests/rest-device.js
- integration-tests/ws-device.js
Status 404 should be returned if device does not exist in device/get
> Status 404 should be returned if device does not exist in device/get

- integration-tests/ws-device.js
Add filters support to WS for device/list action
> Add filters support to WS for device/list action

- integration-tests/ws-command.js
- integration-tests/ws-notification.js
Websocket get/list command/notification
> Websocket get/list command/notification

- integration-tests/rest-device-notification.js
Rest insert notification response changed
> Rest insert notification response changed

- integration-tests/rest-user.js
- integration-tests/ws-auth.js
- integration-tests/ws-device.js
> Websockets: Delete device

- integration-tests/rest-configuration.js
- integration-tests/ws-api-info.js
- integration-tests/ws-command.js
- integration-tests/ws-configuration.js
Websockets: Cluster info (get) and configuration (get, put, delete)
> Websockets: Cluster info (get) and configuration (get, put, delete)

- integration-tests/rest-device-command.js
> Rest: Polling of updated commands

- integration-tests/ws-device.js
- integration-tests/ws-notification.js
WS device/devete returns 500 if {"deviceId": null}
> WS device/devete returns 500 if {"deviceId": null}

- integration-tests/rest-user.js
Get user by id: networks data structure changed
> Get user by id: networks data structure changed

- integration-tests/rest-device-command.js
WS Command List time format parsing error fixed
> WS Command List time format parsing error fixed

- integration-tests/rest-user.js
- integration-tests/ws-user-network.js
- integration-tests/ws-user.js
> WS User API Added

- integration-tests/ws-command.js
WS: no lastUpdated field for command fix
> WS: no lastUpdated field for command fix

- integration-tests/ws-command.js
WS: Action and RequestId returned back to responses
> WS: Action and RequestId returned back to responses

- integration-tests/ws-auth.js
JsonStringWrapper: data field should be json
> WS token issue: invalid login - no response

- integration-tests/rest-device-command.js
- integration-tests/rest-user.js
- integration-tests/ws-user.js
JsonStringWrapper: data field should be json
> JsonStringWrapper: data field should be json

- integration-tests/ws-user.js
> WS User API tests fix

- integration-tests/ws-command.js
- integration-tests/x-round-test-command.js
WS: command/update subscription added
> WS: command/update subscription added

- integration-tests/ws-network.js
DEV-62 - Change sortOrderAsc field for 'network/list' WS query
> DEV-62 - Change sortOrderAsc field for 'network/list' WS query

- integration-tests/rest-configuration.js
- integration-tests/ws-configuration.js
DEV-77 - Improve PUT /configuration/{name} request body
> DEV-77 - Improve PUT /configuration/{name} request body

- integration-tests/common/path.js
- integration-tests/rest-api-info.js
- integration-tests/ws-api-info.js
- integration-tests/x-round-test-command.js
> Dev-99 - hazelcast monitor

- integration-tests/rest-device-command.js
- integration-tests/rest-device-notification.js
- integration-tests/ws-command.js
- integration-tests/ws-device.js
- integration-tests/ws-network.js
- integration-tests/ws-notification.js
- integration-tests/ws-subscription.js
- integration-tests/x-round-test-command.js
- integration-tests/x-round-test-notification.js
DEV-154 - Different result codes for HTTP and WS for user token
> DEV-154 - Different result codes for HTTP and WS for user token

- integration-tests/rest-device-command.js
- integration-tests/rest-device-notification.js
- integration-tests/ws-command.js
- integration-tests/ws-device.js
- integration-tests/ws-network.js
- integration-tests/ws-notification.js
- integration-tests/ws-subscription.js
- integration-tests/x-round-test-command.js
- integration-tests/x-round-test-notification.js
Reverts devicehive/devicehive-tests#83
> Revert "DEV-154 - Different result codes for HTTP and WS for user token"

- integration-tests/rest-device.js
- integration-tests/ws-device.js
Add validation for deviceId field in DeviceVO/DeviceUpdate (in annotation)
> DEV-149 Add validation for deviceId field in DeviceVO/DeviceUpdate (in annotation)

- integration-tests/ws-command.js
> DEV-TEST-FIX - Timeout added

- integration-tests/ws-network.js
Here we have BREAKING changes. Should be merged in new release.
> DEV-160 - WS return 500 when network not found

- integration-tests/ws-command.js
- integration-tests/ws-notification.js
DEV-190 - WS request that kills server fixed
> DEV-190 - WS request that kills server fixed

- integration-tests/rest-device-command.js
- integration-tests/rest-device-notification.js
- integration-tests/ws-command.js
- integration-tests/ws-notification.js
DEV-233 - Add networkId to websocket notification message
> DEV-233 - Add networkId to websocket notification message

- integration-tests/rest-device-command.js
- integration-tests/rest-device-notification.js
- integration-tests/ws-command.js
- integration-tests/ws-notification.js
Reverts devicehive/devicehive-tests#95
> Revert "DEV-233 - Add networkId to websocket notification message"

- config.json
- integration-tests/common/utils.js
- integration-tests/common/websocket.js
- integration-tests/rest-api-info.js
- integration-tests/rest-device-command.js
- integration-tests/rest-device-notification.js
- integration-tests/rest-device.js
- integration-tests/rest-jwt.js
- integration-tests/ws-auth.js
- integration-tests/ws-command.js
- integration-tests/ws-notification.js
- integration-tests/x-round-test-command.js
- integration-tests/x-round-test-notification.js
DEV-163 - Extract Authentication module into a separate microservice
> DEV-163 - Extract Authentication module into a separate microservice

- integration-tests/rest-configuration.js
- integration-tests/rest-jwt.js
- integration-tests/x-round-test-notification.js
> DEV-183 - Auth test fix

- integration-tests/ws-command.js
- integration-tests/ws-notification.js
DEV-288 - WS time filter not working
> DEV-288 - WS time filter not working

- integration-tests/ws-command.js
- integration-tests/ws-notification.js
DEV-288 - WS time filter not working (part 2)
> DEV-288 - WS time filter not working (part 2)

- config.json
- integration-tests/common/path.js
- integration-tests/common/utils.js
- integration-tests/common/websocket.js
- integration-tests/rest-device-command.js
- integration-tests/rest-jwt.js
- integration-tests/rest-plugin.js
- integration-tests/ws-auth.js
- integration-tests/ws-command.js
- integration-tests/ws-notification.js
- integration-tests/x-round-test-command.js
DEV-184 - Make a registration endpoint for plugins
> DEV-184 - Make a registration endpoint for plugins

- integration-tests/rest-plugin.js
> DEV-184 - Tests fixed

- integration-tests/ws-api-info.js
Added tests for the malformed Json in the WebSocket request.
> DEV-323; https://support.dataart.com/browse/DEV-323;

- config.json
- integration-tests/rest-jwt.js
- integration-tests/rest-plugin.js
DEV-306 - Make tests for plugin configurable
> DEV-306 - Make tests for plugin configurable

- integration-tests/rest-jwt.js
- integration-tests/rest-plugin.js
DEV-306 - Plugin management service fix
> DEV-306 - Plugin management service fix

- integration-tests/rest-configuration.js
- integration-tests/ws-configuration.js
Configuration name length exceeded error.
> DEV-330; https://support.dataart.com/browse/DEV-330;

- integration-tests/rest-plugin.js
https://support.dataart.com/browse/DEV-361;
> Feature: Plugin management service: remove healthchecks;

- integration-tests/common/websocket.js
> WS response timer fix

- integration-tests/common/utils.js
- integration-tests/rest-plugin.js
https://support.dataart.com/browse/DEV-404;
Feature: Plugin management service: implement 'plugin/count' method;
https://support.dataart.com/browse/DEV-405;
> Feature: Plugin management service: implement '/plugin/list' API method;

- integration-tests/common/path.js
- integration-tests/common/utils.js
- integration-tests/rest-jwt.js
- integration-tests/rest-plugin.js
https://support.dataart.com/browse/DEV-443;
Integration tests for plugin delete and update regarding proper permissions' management implemented.
> Feature: Integration tests for plugin delete and update;

- integration-tests/rest-plugin.js
- package-lock.json
Tests improvements (calling "done" in the right place)
> Tests improvements
